### ISSUE TITLE
Better Combat animations breaking in survival/when losing durability?

### ISSUE THREAD

**Issue by NolanHewitt** [Partonetrain/botaniacombat#10]
It seems like the terra weapons break their animations when they loose durability from making the beam appear? 

https://github.com/user-attachments/assets/f108afa4-5314-449e-a171-f70c3ac804cd

**Comment by NolanHewitt** [comment]
I have a modset installed here in this video, but I did test this after using a setup of only botania, better combat, botania combat, and the requirements for those three mods and the issue remains.

**Comment by Partonetrain** [comment]
You are correct in your diagnosis of the issue, but it's not really something I can fix. BetterCombat expects the item to not change durability. This doesn't happen if the player has a Mana Tablet in their inventory.

**Comment by NolanHewitt** [comment]
Ah ok, I see its fine with any mana source in my inventory.
