### ISSUE TITLE
3.0 crashing when ran alongside Ferritecore

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/botaniacombat#14]
Hiya. I ran into a crash when I updated to 3.0, and narrowed it down to a conflict between BotaniaCombat and Ferritecore.

Crashlog: https://mclo.gs/x5O0VmR

**Comment by Partonetrain** [comment]
Coincidentally I ran into the same issue with CIT Resewn, apparently classloading ResourceLocation in mod init is a bad idea

Try https://cdn.discordapp.com/attachments/1079855089767952496/1276979228470018059/botaniacombat-1.20.1-3.0.1b.jar?ex=66cb7f15&is=66ca2d95&hm=5c872d7190afcc19c9b09946765b5bd68ccc61ae6e604cf8e4ad259e9ed9c287& 

I won't upload this to CF/MR just yet until I know there's not more issues

**Comment by anoomolu** [comment]
No crash with that build, and I didn't see any issues with BC + Ranged Weapon API items.

**Comment by NolanHewitt** [comment]
I encountered the same crash. That linked build (3.0.1) does work without issue for me though.

**Comment by Partonetrain** [comment]
fixed in 3.0.2
