### ISSUE TITLE
Config Option Request: Odin Ring and Tiara

### ISSUE THREAD

**Issue by NolanHewitt** [Partonetrain/botaniacombat#15]
I saw the new version has some options to change stuff from vanilla botania like how much health the odin ring gives or the damage of certain attacks. Would it be possible to add to that the option to disable odin ring's immunity to environmental damage and falling damage? I always felt like this part of it could make the game a little too easy. 
Similarly with the tiara I think some configurable option to nerf it would be nice though with that one I'm not sure what that would be. Faster Mana Drain? Reduced Flight Time? I'm not sure.

**Comment by Partonetrain** [comment]
The first thing can already be changed with a datapack by emptying the following tag
https://github.com/VazkiiMods/Botania/blob/1.20.x/Xplat/src/generated/resources/data/botania/tags/damage_type/ring_of_odin_immune.json
The second thing is probably doable

**Comment by NolanHewitt** [comment]
Oh interesting, I had no idea that tag existed. Thank you for that!

**Comment by Partonetrain** [comment]
added in 3.0.2
