### ISSUE TITLE
Versions >= 2.2.2 crash due to failed Mixin

### ISSUE THREAD

**Issue by Goldscar1** [Partonetrain/botaniacombat#17]
This is probably due to misspellings of botaniacombat -> botanaicombat in Code like here:

- [DamagingLensMixin](https://github.com/Partonetrain/botaniacombat/blob/59cbd0842f46a899b3774a1976df305d62e445b5/src/main/java/info/partonetrain/botaniacombat/mixin/nerf/DamagingLensMixin.java#L17)

- [FallingStarEntityMixin](https://github.com/Partonetrain/botaniacombat/blob/59cbd0842f46a899b3774a1976df305d62e445b5/src/main/java/info/partonetrain/botaniacombat/mixin/nerf/FallingStarEntityMixin.java#L12)

- [ThornChakramEntityMixin](https://github.com/Partonetrain/botaniacombat/-blob/59cbd0842f46a899b3774a1976df305d62e445b5/src/main/java/info/partonetrain/botaniacombat/mixin/nerf/ThornChakramEntityMixin.java#L12)
- [MagicMissileEntityMixin](https://github.com/Partonetrain/botaniacombat/blob/59cbd0842f46a899b3774a1976df305d62e445b5/src/main/java/info/partonetrain/botaniacombat/mixin/nerf/MagicMissileEntityMixin.java#L13)
- [BabylonWeaponEntityMixin](https://github.com/Partonetrain/botaniacombat/blob/59cbd0842f46a899b3774a1976df305d62e445b5/src/main/java/info/partonetrain/botaniacombat/mixin/nerf/BabylonWeaponEntityMixin.java#L12)

Crash Report is attached here
[crash-2024-09-02_11.53.22-client.txt](https://github.com/user-attachments/files/16836061/crash-2024-09-02_11.53.22-client.txt)

**Comment by Partonetrain** [comment]
The game is trying to locate RangedWeaponApi classes but fails. It's supposed to be possible to play without RangedWeaponAPI but it looks like I made a mistake in 3.0.

Mixin method names have nothing to do with it, but that's a good catch. I don't know how I managed to typo that many times...

**Comment by Partonetrain** [comment]
Uploading 3.0.4 now, let me know if it fixes it

**Comment by Goldscar1** [comment]
That did indeed fix it, thank you very much!
