### ISSUE TITLE
Crossbows not showing up in lexicon

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/botaniacombat#3]
Heya. The recent fix to make crossbows only show up when Ranged Weapon API seems to be working a little too well - even with the mod installed, the entries are hidden. This is due to accidentally replacing _ with - in the mod:ranged_weapon_api line in patchouli_books ^^

edit: unrelated issue but didn't want to spam the issues page - the crystal crossbow recipe currently crafts a livingwood crossbow.

**Comment by Partonetrain** [comment]
Thanks again for the catch. I managed to confuse the modid for the modrinth
slug...
