### ISSUE TITLE
Suggestion - make Slaughtersaw viable for regular use

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/botaniacombat#4]
Hiya! I was retexturing the Slaughtersaw to match FD knives in my pack, and noticed that some of the stats and enchantability differed from regular FD knives and Manasteel tools. The attack speed is higher than an iron knife (2.2 compared to 2), the attack damage is lower (2 compared to 3.5) and durability much higher than other manasteel tools (720 compared to 300). Seems like the Slaughtersaw can't take Backstabbing as an enchant either.

I wanted to suggest making the Slaughtersaw have the same stats as a FD knife of the same tier, the stats mentioned above. I appreciate that the lexicon entry mentions that it isn't that useful for creatures that don't drop meat, but I'd imagine it would still be a decent weapon should one want to use it.

**Comment by Partonetrain** [comment]
I think it's okay if the stats and functionality differ slightly from the standard - it gives it more "personality". I should probably make the stats configurable, though.

It definetely shouldn't have 720 durability - it's registered with BotaniaCombatTiers.MANASTEEL_TIER, which should be 300.

I want to try and figure out if I can add backstabbing compat without explicitly depending on FD, but I will try some things.

**Comment by Partonetrain** [comment]
I added configuration for practically all stats in the latest commit.

However, unfortunately, FD Refabricated [overrides Backstabbing's canEnchant method](https://github.com/MehVahdJukaar/FarmersDelight/blob/1.20/src/main/java/vectorwing/farmersdelight/common/item/enchantment/BackstabbingEnchantment.java#L25-L30) in a way that the Slaughtersaw can't be made to work with Backstabbing via anvil or /enchant without depending on the mod (enchanting table works fine, though)

It looks like I will have to make FD an optional dependency

**Comment by anoomolu** [comment]
I appreciate the modularity you've given BotaniaCombat, it's nice being able to pick and choose what parts you want in your pack. Thanks for implementing these configs <3

**Comment by Partonetrain** [comment]
~~I am uploading 2.0.0 to CF and MR. I think what I will do is create yet another extremely specific use-case mod to allow arbitrary items to be able to accept Backstabbing~~ I discussed this with MerchantPug and FD-Refabricated will be updated to check for #c:knives. Follow the issue here: https://github.com/MehVahdJukaar/FarmersDelight/issues/22

**Comment by anoomolu** [comment]
> I think it's okay if the stats and functionality differ slightly from the standard - it gives it more "personality". I should probably make the stats configurable, though.

Would it be possible to allow integer values for weapon damage modifiers? I'm trying to lower a weapons damage by 1.5 relative to the material tier. Other than that, the config's perfect for probably most use cases out there 😄

**Comment by Partonetrain** [comment]
I think you meant Double, and yes, that's possible. I am unsure if configs from 2.0.0 will transfer, but considering I'll be making this change this early I think it'll be fine.

**Comment by Partonetrain** [comment]
Turns out it's only possible with `DiggerItem`s. Farmer's Delight knives are DiggerItems anyway, so I will be changing the superclass of Slaughtersaw.

**Comment by Partonetrain** [comment]
Will be fixed in 2.1.0, uploading shortly
