### ISSUE TITLE
Slaughtersaw unable to be used on Cutting Board

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/botaniacombat#6]
Seems like the knife tag isn't correct - tagging the Slaughtersaw under items/tools/knives seems to restore functionality.
For reference: https://github.com/MehVahdJukaar/FarmersDelight/blob/1.20/src/generated/resources/data/c/tags/items/tools/knives.json

What is observed in-game:
![image](https://github.com/Partonetrain/botaniacombat/assets/77850233/531961d4-3824-403d-a039-fe15a7d15f05)

**Comment by Partonetrain** [comment]
Seems FD isn't using [the convention.](https://fabricmc.net/wiki/tutorial:tags#conventional_tags). 
I will release a hotfix when I get around to it.
