### ISSUE TITLE
Gaia Gift conditions?

### ISSUE THREAD

**Issue by NolanHewitt** [Partonetrain/botaniacombat#9]
Apologies if this is the wrong place to ask this, but what exactly are the conditions to get the gaia gift items? I can't seem to figure it out.

Also unrelated, but someone was able to get the star caller to work with better combat on forge. Not sure if those fixes will work with the fabric version but might be worth taking a look at. https://github.com/vertexcubed/BetterCombatFixes/tree/main/src/main/java/com/vivividly/bc_fixes/botania

**Comment by Partonetrain** [comment]
The exact criteria can be seen in the advancements:
https://github.com/Partonetrain/botaniacombat/tree/main/src/main/resources/data/botania/advancements/challenge

Also, thanks for that pointer. I'll look into it.
